### ISSUE TITLE
Vtweaks causing ticking entities

### ISSUE THREAD

**Issue by Daphtaos** [oitsjustjose/V-Tweaks#117] opened 2024-05-20 22:03 UTC
Hello, after doing a bit of troubleshooting with the forge discord team on a server crash log, we found that Vtweaks was causing (creating ?) ticking entities that were crashing the server. I am putting here the log in question if it can help. I was pushed to report this issue to the mod author, I do not know if it is a known issue tho, sorry if it is the case and my lack of awareness if so. Have a great day !
[latest.log](https://github.com/oitsjustjose/V-Tweaks/files/15382089/latest.log)

**Comment by jose-frg** [comment] 2024-05-21 14:12
Duplicate of #115 -- you can always disable the Trader Stonks feature in `vtweaks-common.toml` to fix this immediately - I'll probably be killing this buggy and cursed feature in the next update when I have time :)

**Comment by oitsjustjose** [comment] 2024-05-21 14:13
Duplicate of #115 - you can fix this immediately by disabling the TraderStonks feature in `vtweaks-common.toml` as an immediate fix until I remove this buggy feature entirely. So sorry about the inconvenience!

**Closed as completed by oitsjustjose** 2024-05-21 14:13 UTC
