### ISSUE TITLE
Imperishable bug

### ISSUE THREAD

**Issue by EternalOne11** [oitsjustjose/V-Tweaks#72] opened 2020-05-24 14:20 UTC
The imperishable enchant is only taking 1 level to apply in the 1.15.2 build. Is this a bug or did you change it to work like other enchants?

**Comment by oitsjustjose** [comment] 2020-06-03 00:39
Oh like when you apply it to a tool in an anvil? Making sure it's not that it's able to get it via enchanting.

**Comment by oitsjustjose** [comment] 2020-06-26 02:02
I have just tested this for a good bit and I can't reproduce. Closing for now, let me know if you find any other mods conflicting with enchantments and causing this issue! 😀

**Closed as completed** 2020-06-26 02:02 UTC
